const LIB_META={version:'v2.0',updated:'2026-09-18'};
const PAPERS=[

{id:'S01',module:'空间自相关与聚集探测',priority:5,title:'Notes on Continuous Stochastic Phenomena',authors:'Moran PAP',journal:'Biometrika',year:1950,methods:['Global Moran’s I','空间自相关','随机化检验'],question:'整个广东的区县癌症率是否呈现超出随机期望的全局空间自相关？',data:'区域属性值与预先定义的空间权重矩阵',design:'经典空间统计方法',sample:'方法学文章',flow:'选择稳定的风险指标\n→ 构造邻接/距离权重W\n→ 标准化变量\n→ 计算Global Moran’s I\n→ 置换检验\n→ 权重矩阵敏感性分析',result:'Moran’s I回答“全局上是否聚集”，不能定位具体热点，也不能校正小区县率的高方差。',innovation:'奠定区域空间自相关检验基础。',limitations:'结果依赖空间权重；直接对小样本粗率计算可能被不稳定率驱动。',reuse:'先对经验贝叶斯平滑率或模型后验风险做探索；至少比较Queen、Rook和距离权重。',url:'https://doi.org/10.1093/biomet/37.1-2.17'},
{id:'S02',module:'空间自相关与聚集探测',priority:5,title:'Local Indicators of Spatial Association—LISA',authors:'Anselin L',journal:'Geographical Analysis',year:1995,methods:['Local Moran’s I','LISA','热点/离群点','置换检验'],question:'哪些区县属于高-高、低-低聚集，哪些是高-低或低-高空间离群点？',data:'区县级风险指标与空间权重矩阵',design:'局部空间关联方法',sample:'方法学文章',flow:'全局检验\n→ 计算每个区县Local Moran’s I\n→ 条件随机化/置换\n→ 多重检验控制\n→ LISA聚类图\n→ 权重与阈值敏感性',result:'LISA把全局统计量分解到单个空间单元，用于发现局部聚集与空间离群。',innovation:'把“是否聚集”扩展为“聚集在哪里以及属于什么类型”。',limitations:'局部检验数量多，显著性和聚类类型对权重、分级及多重比较敏感。',reuse:'适合生成广东区县高-高/低-低图，但应同时报告FDR校正和不同邻接定义的稳定性。',url:'https://doi.org/10.1111/j.1538-4632.1995.tb00338.x'},
{id:'S03',module:'空间自相关与聚集探测',priority:5,title:'A Spatial Scan Statistic',authors:'Kulldorff M',journal:'Communications in Statistics—Theory and Methods',year:1997,methods:['SaTScan','Poisson扫描','RR','LLR','Monte Carlo'],question:'在不知道聚集区位置和大小的情况下，如何同时搜索并检验异常高风险空间窗口？',data:'区域病例数、期望病例/人口人时、坐标或邻接信息',design:'空间扫描统计方法',sample:'方法学文章',flow:'按年龄/性别计算期望数\n→ Poisson离散模型\n→ 移动可变大小窗口\n→ 计算窗口内外RR与LLR\n→ Monte Carlo显著性\n→ 最大窗口比例敏感性',result:'扫描统计量在校正多重搜索后识别最可能及次级聚集区。',innovation:'把未知位置、未知尺度的聚集识别统一为似然比搜索问题。',limitations:'圆形窗口可能吞并非风险区；最大窗口过大会产生难解释的大聚集区。',reuse:'广东分析建议以病例数为结局、人口人时为offset，并把最大空间窗设为10%、25%、50%做稳定性分析。',url:'https://doi.org/10.1080/03610929708831995'},
{id:'S04',module:'空间自相关与聚集探测',priority:5,title:'Evaluating Cluster Alarms: A Space–Time Scan Statistic and Brain Cancer in Los Alamos, New Mexico',authors:'Kulldorff M, Athas WF, Feuer EJ, Miller BA, Key CR',journal:'American Journal of Public Health',year:1998,methods:['时空扫描','圆柱窗口','LLR','Monte Carlo'],question:'怎样检验某些地区在某段时间内同时出现异常癌症风险，而不是事后挑选出来的偶然高值？',data:'地区×时间病例数及对应人口/期望数',design:'时空聚集探测方法与案例',sample:'脑癌聚集报警案例',flow:'建立空间×时间圆柱窗口\n→ 比较窗内外发病风险\n→ 计算LLR和RR\n→ Monte Carlo校正搜索偏倚\n→ 报告时间段与空间范围',result:'时空扫描可控制预选与多重搜索偏倚，用于判断聚集警报是否值得深入调查。',innovation:'把空间扫描扩展到时空联合窗口。',limitations:'时间分辨率、最大窗口、重叠聚集规则和人口迁移都会改变结果。',reuse:'与研究图一致：性别×年龄×年度作为分层或协变量；先固定区县边界和可比登记年份。',url:'https://doi.org/10.2105/AJPH.88.9.1377'},
{id:'S05',module:'空间自相关与聚集探测',priority:4,title:'Evaluating Spatial Methods for Investigating Global Clustering and Cluster Detection of Cancer Cases',authors:'Huang L, Pickle LW, Das B',journal:'Statistics in Medicine',year:2008,methods:['方法比较','Moran’s I','LISA','SaTScan','功效'],question:'面对不同形状、尺度与样本量的癌症聚集，Moran、LISA和扫描统计量各有什么性能差异？',data:'美国癌症死亡空间模式与模拟数据',design:'空间方法模拟比较',sample:'州/县级多种癌症空间模式',flow:'构造8类聚集模式\n→ 改变样本量与RR\n→ 比较全局与局部方法\n→ 评价功效和定位精度\n→ 匹配研究目的选方法',result:'全局聚集检验和局部聚集探测回答不同问题；显著全局相关不等于存在可定位热点，反之亦然。',innovation:'给出癌症区域数据上选用空间检验的直接比较证据。',limitations:'模拟情景不能覆盖广东不规则行政区、登记缺失和人口流动的全部复杂性。',reuse:'支持采用“Global Moran→LISA探索→SaTScan确认→Bayesian风险图”的多方法三角验证。',url:'https://doi.org/10.1002/sim.3342'},

{id:'B01',module:'贝叶斯疾病制图与空间回归',priority:5,title:'Bayesian Image Restoration, with Two Applications in Spatial Statistics',authors:'Besag J, York J, Mollié A',journal:'Annals of the Institute of Statistical Mathematics',year:1991,methods:['BYM模型','CAR','空间平滑','Poisson'],question:'如何在小区域病例稀疏时同时利用邻近地区信息和区县自身异质性稳定估计相对风险？',data:'区域病例计数、期望数和邻接矩阵',design:'经典贝叶斯空间层级模型',sample:'方法学文章',flow:'Yᵢ~Poisson(Eᵢθᵢ)\n→ log θᵢ=截距+结构化CAR效应+非结构化效应\n→ 先验与后验估计\n→ 风险图与不确定性',result:'BYM通过结构化与非结构化随机效应平滑小区域风险，减少粗SIR的随机波动。',innovation:'成为区域疾病制图和空间生态回归的标准起点。',limitations:'原始BYM两个随机效应方差难辨识、尺度依赖，优先考虑BYM2参数化。',reuse:'广东区县癌症计数主模型的理论基础；输出后验RR、95%CrI和超阈值概率。',url:'https://doi.org/10.1007/BF00116466'},
{id:'B02',module:'贝叶斯疾病制图与空间回归',priority:5,title:'Disease Mapping and Spatial Regression with Count Data',authors:'Wakefield J',journal:'Biostatistics',year:2007,methods:['空间Poisson回归','生态偏倚','空间混杂','敏感性分析'],question:'区域癌症计数怎样做疾病制图与协变量回归，同时避免把生态关联误解为个体因果效应？',data:'区域病例计数、期望数、空间协变量与邻接结构',design:'方法学综述与模型改进',sample:'苏格兰唇癌数据示例',flow:'构造期望数与offset\n→ Poisson/负二项模型\n→ 空间随机效应\n→ 协变量效应\n→ 先验/权重敏感性\n→ 检查生态偏倚与空间混杂',result:'空间层级模型可稳健估计区域风险，但生态回归更危险；协变量和残余空间效应都具有空间结构时，效应估计高度依赖模型。',innovation:'把疾病制图、生态偏倚、相互标准化和空间混杂放入统一批判框架。',limitations:'区域关联不能直接解释为个体暴露效应；数据本身常不能唯一选择正确空间相关结构。',reuse:'这是医疗可及性、GDP、PM2.5等进入贝叶斯空间模型前的必读文献。',url:'https://doi.org/10.1093/biostatistics/kxl008'},
{id:'B03',module:'贝叶斯疾病制图与空间回归',priority:5,title:'An Intuitive Bayesian Spatial Model for Disease Mapping that Accounts for Scaling',authors:'Riebler A, Sørbye SH, Simpson D, Rue H',journal:'Statistical Methods in Medical Research',year:2016,methods:['BYM2','PC prior','INLA','方差分解'],question:'如何让空间结构效应与非结构效应可解释、可缩放，并设置稳定的复杂度惩罚先验？',data:'区域计数、期望数与邻接图',design:'Bayesian空间模型方法研究',sample:'方法学与模拟案例',flow:'缩放ICAR效应\n→ BYM2重参数化\n→ 总方差τ与空间比例φ\n→ PC先验\n→ INLA拟合\n→ 后验风险及敏感性',result:'BYM2使总变异和空间变异比例更易解释，先验可跨不同地图尺度使用。',innovation:'解决原始BYM的不可辨识和尺度问题，是现代疾病制图的推荐默认模型。',limitations:'仍依赖邻接定义；过强平滑可能掩盖真实边界或小热点。',reuse:'建议作为广东区县单癌种年度/合并年度风险图的主模型。',url:'https://doi.org/10.1177/0962280216660421'},
{id:'B04',module:'贝叶斯疾病制图与空间回归',priority:5,title:'Bayesian Modelling of Inseparable Space-Time Variation in Disease Risk',authors:'Knorr-Held L',journal:'Statistics in Medicine',year:2000,methods:['时空BYM','RW1/RW2','空间×时间交互','疾病制图'],question:'如何分解癌症风险的总体时间趋势、稳定空间差异和不同类型的时空交互？',data:'地区×年份病例数、期望数与邻接关系',design:'贝叶斯时空疾病制图方法',sample:'1968—1988年Ohio肺癌示例',flow:'空间主效应\n→ 时间结构/非结构效应\n→ 四类空间×时间交互\n→ 比较模型拟合与复杂度\n→ 后验RR与趋势图',result:'四类交互可识别特定地区偏离总体趋势的风险变化。',innovation:'建立区域疾病风险时空分解的经典框架。',limitations:'参数多，稀疏区县×年份数据可能辨识不足；需约束、先验和模型比较。',reuse:'当广东有足够连续可比年度时，用BYM2+RW1/RW2+Knorr-Held交互替代仅靠重复SaTScan。',url:'https://doi.org/10.1002/1097-0258(20000915/30)19:17/18%3C2555::AID-SIM587%3E3.0.CO;2-%23'},
{id:'B05',module:'贝叶斯疾病制图与空间回归',priority:4,title:'Approximate Bayesian Inference for Latent Gaussian Models by Using Integrated Nested Laplace Approximations',authors:'Rue H, Martino S, Chopin N',journal:'Journal of the Royal Statistical Society: Series B',year:2009,methods:['INLA','潜在高斯模型','Laplace近似','快速贝叶斯计算'],question:'如何不依赖长时间MCMC，高效拟合BYM2和复杂时空潜在高斯模型？',data:'适用于空间、时空、纵向等潜在高斯模型',design:'计算统计方法',sample:'方法学文章',flow:'定义潜在高斯层级模型\n→ 嵌套Laplace近似\n→ 超参数数值积分\n→ 后验边际分布\n→ 与MCMC/诊断比较',result:'INLA可快速给出潜在变量和超参数的近似后验边际分布。',innovation:'使大规模区域时空疾病制图在普通计算环境中可行。',limitations:'仅适用于潜在高斯模型类；近似精度仍需后验预测和必要时MCMC核验。',reuse:'实现工具建议R-INLA；用于BYM2、RW1/RW2和空间×时间交互。',url:'https://doi.org/10.1111/j.1467-9868.2008.00700.x'},

{id:'A01',module:'医疗资源空间可及性',priority:5,title:'Measures of Spatial Accessibility to Health Care in a GIS Environment: Synthesis and a Case Study in the Chicago Region',authors:'Luo W, Wang F',journal:'Environment and Planning B',year:2003,methods:['2SFCA','重力模型','GIS网络','敏感性分析'],question:'如何同时考虑医疗供给、人口需求和出行阻抗，量化居民潜在医疗可及性？',data:'医疗机构位置与容量、人口需求点、路网出行时间',design:'可及性方法综合与案例',sample:'Chicago地区基层医生案例',flow:'路网最短时间矩阵\n→ 设定服务阈值\n→ 机构端供需比\n→ 居民端汇总可达供给\n→ 与重力模型比较\n→ 阈值/摩擦系数敏感性',result:'2SFCA是重力模型的一种可解释形式，能同时反映跨行政边界的供需关系。',innovation:'奠定GIS环境下2SFCA医疗可及性测量框架。',limitations:'单一阈值内默认等权，阈值外为零；结果强依赖路网、容量定义和距离衰减。',reuse:'不要只算“最近医院时间”；同步计算肿瘤专科资源容量/服务人口的E2SFCA指标。',url:'https://doi.org/10.1068/b29120'},
{id:'A02',module:'医疗资源空间可及性',priority:5,title:'An Enhanced Two-Step Floating Catchment Area Method for Measuring Spatial Accessibility to Primary Care Physicians',authors:'Luo W, Qi Y',journal:'Health & Place',year:2009,methods:['E2SFCA','距离衰减','分段权重','重力模型'],question:'怎样修正传统2SFCA在服务圈内人人可及性相同的不现实假设？',data:'医疗供给、人口需求、多时间带出行时间',design:'可及性方法改进',sample:'Illinois基层医生案例',flow:'划分多个出行时间带\n→ 为时间带设置衰减权重\n→ 计算加权供需比\n→ 汇总居民可达资源\n→ 比较短缺区识别',result:'E2SFCA通过时间带衰减获得更细致、符合直觉的可及性空间格局。',innovation:'把距离衰减引入2SFCA，同时保持供需比的易解释性。',limitations:'时间带和权重需本地出行行为校准；照搬国外阈值可能错分广东城乡。',reuse:'图中“不同交通方式选择比例加权”可进一步做多模式E2SFCA，并分城/乡设置阈值。',url:'https://doi.org/10.1016/j.healthplace.2009.06.002'},
{id:'A03',module:'医疗资源空间可及性',priority:4,title:'A Three-Step Floating Catchment Area Method for Analyzing Spatial Access to Health Services',authors:'Wan N, Zou B, Sternberg T',journal:'International Journal of Geographical Information Science',year:2012,methods:['3SFCA','供需竞争','距离阻抗','GIS'],question:'当居民可选择多家医院时，如何避免把同一人口需求重复分配给所有机构而高估需求？',data:'供给点、需求点、路网时间及距离衰减',design:'可及性方法改进',sample:'Austin–San Antonio基层医疗案例',flow:'按阻抗分配居民选择概率\n→ 计算校正需求\n→ 机构供需比\n→ 居民端汇总\n→ 与E2SFCA比较',result:'3SFCA加入竞争分配，减轻需求重复计算并改善短缺区识别。',innovation:'在E2SFCA前增加人口选择/竞争校正步骤。',limitations:'选择概率模型和衰减参数需要数据支持；复杂不等于一定更有效。',reuse:'若广东患者跨区县就医明显，3SFCA比最近医院或普通2SFCA更贴近实际。',url:'https://doi.org/10.1080/13658816.2011.624987'},
{id:'A04',module:'医疗资源空间可及性',priority:4,title:'Spatial Accessibility in Suboptimally Configured Health Care Systems: A Modified Two-Step Floating Catchment Area Metric',authors:'Delamater PL',journal:'Health & Place',year:2013,methods:['M2SFCA','资源配置','距离摩擦','供需失配'],question:'医疗机构布局并非最优时，怎样避免传统FCA高估整个系统的可及性？',data:'医疗供给、人口需求和出行阻抗',design:'可及性方法研究',sample:'模拟与Michigan急性医院案例',flow:'识别传统FCA隐含最优配置假设\n→ 供给侧配置折扣\n→ M2SFCA\n→ 模拟与案例比较',result:'M2SFCA把资源空间配置低效纳入可及性估计，减少系统性高估。',innovation:'区分“资源存在”与“资源被合理配置”。',limitations:'指标解释和参数化较2SFCA复杂；仍属于潜在可及性而非真实利用。',reuse:'可作为广东肿瘤专科床位、放疗设备等资源布局不均的敏感性分析。',url:'https://doi.org/10.1016/j.healthplace.2013.07.012'},
{id:'A05',module:'医疗资源空间可及性',priority:4,title:'Spatial Accessibility of Primary Care: Concepts, Methods and Challenges',authors:'Guagliardo MF',journal:'International Journal of Health Geographics',year:2004,methods:['可及性概念','供给/需求','GIS','方法综述'],question:'地理可及性与医疗服务的可负担性、可接受性和实际利用有何区别？',data:'医疗地理方法与案例综述',design:'概念与方法综述',sample:'方法学文章',flow:'界定潜在/现实可及性\n→ 区分空间与非空间维度\n→ 评价供给、需求、距离指标\n→ 讨论GIS方法与挑战',result:'出行时间只覆盖可及性的一部分；资源容量、人口需求、支付、转诊和实际利用需要分开解释。',innovation:'为可及性指标的概念效度提供清晰框架。',limitations:'聚焦基层医疗，肿瘤专科分级诊疗需要进一步定义服务能力。',reuse:'广东研究应把“最近医院时间”和“供需加权可及性”作为不同暴露，不能混为同一指标。',url:'https://doi.org/10.1186/1476-072X-3-3'},

{id:'E01',module:'社会环境与癌症负担关联',priority:5,title:'Trends and Patterns of Disparities in Cancer Mortality Among US Counties, 1980–2014',authors:'Mokdad AH, Dwyer-Lindgren L, Fitzmaurice C, et al.',journal:'JAMA',year:2017,methods:['小区域估计','时空模型','年龄标化','县级癌症地图'],question:'怎样在长时间、多个癌种和所有县范围内稳定估计癌症死亡并展示空间差异？',data:'NCHS死亡记录、人口普查及县级协变量',design:'县级人口模型研究',sample:'1980—2014年约1951万癌症死亡，29类癌症',flow:'死因清理与再分配\n→ 年龄/性别/县/年分层\n→ 验证的小区域模型\n→ 不确定区间\n→ 癌种热点和趋势地图',result:'美国县级癌症死亡差异巨大且癌种热点位置不同，说明全国/省平均会掩盖局部负担。',innovation:'顶刊级小区域癌症负担制图范例，重视死因质量、不确定性和跨年可比性。',limitations:'模型依赖和死亡登记错误可能影响局部估计；结果不直接证明地区因素的因果作用。',reuse:'广东应把区县RR/率的不确定性与地图同时展示，避免只做分级设色图。',url:'https://doi.org/10.1001/jama.2016.20324'},
{id:'E03',module:'社会环境与癌症负担关联',priority:5,title:'Geographical Variation in Social Determinants of Female Breast Cancer Mortality Across US Counties',authors:'Anderson T, Herrera D, Mireku F, et al.',journal:'JAMA Network Open',year:2023,methods:['Local Moran’s I','MGWR','空间非平稳','社会决定因素'],question:'医疗、社会经济、环境与乳腺癌死亡的关联是否在不同地点和空间尺度上变化？',data:'2176个美国县乳腺癌死亡及18项人口、环境、生活方式和医疗可及性变量',design:'地理空间横断面研究',sample:'SEER 2015—2019县级年龄校正死亡率',flow:'LISA聚集图\n→ OLS基准模型\n→ MGWR估计局部系数与尺度\n→ 比较拟合\n→ 绘制空间非平稳关联',result:'乳腺筛查和肥胖关联较稳定，食物环境、运动机会、医生资源和夜间灯光等关联的大小与显著性随地区变化。',innovation:'与研究图中的夜间灯光、医疗资源、社会经济和局部关联高度一致，是顶刊应用范例。',limitations:'约三分之一县因小计数抑制而排除；MGWR偏探索，局部多重检验、共线性和因果解释需谨慎。',reuse:'可作为探索性补充；主结果建议由BYM2/时空贝叶斯回归给出，MGWR用于显示非平稳性。',url:'https://doi.org/10.1001/jamanetworkopen.2023.33618'},
{id:'E04',module:'社会环境与癌症负担关联',priority:5,title:'Changes in Geographic Variation and Socioeconomic Inequalities in Esophageal Cancer Mortality in China, 1973–2017',authors:'Ran X, Zheng R, Zeng H, et al.',journal:'Cancer Epidemiology, Biomarkers & Prevention',year:2023,methods:['中国县级登记','热点分析','负二项回归','社会经济不平等'],question:'中国县级食管癌死亡的空间差异如何变化，农村性、GDP和教育水平与死亡率有何关联？',data:'全国死亡调查与肿瘤登记；782个县；GDP、教育、城乡属性',design:'县级长期比较与生态关联研究',sample:'1973—1975与2015—2017两个时期',flow:'年龄标化死亡率\n→ 县级变化与不平等指标\n→ Global Moran/Getis-Ord热点\n→ 负二项计数回归\n→ 性别分层',result:'多数县死亡下降且地区差距缩小，但高风险聚集仍存在；农村、低GDP和低教育与较高死亡相关。',innovation:'与拟开展的广东区县研究最接近的中国国家癌症中心应用模板。',limitations:'两个时期数据源不同、县级覆盖不完整；非空间负二项模型可能残留空间相关，生态关联不能个体化解释。',reuse:'可直接借鉴数据表结构、不平等指标和中国情境讨论，再用BYM2空间随机效应升级关联模型。',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10543962/'},
{id:'E05',module:'社会环境与癌症负担关联',priority:4,title:'Influence of Timeliness and Receipt of First Treatment on Geographic Variation in Non-Small Cell Lung Cancer Mortality',authors:'Wah W, Stirling RG, Ahern S, Earnest A',journal:'International Journal of Cancer',year:2021,methods:['Bayesian空间多水平模型','个体+地区变量','地理变异分解','肺癌死亡'],question:'肺癌死亡的地理差异中，及时治疗、是否治疗、患者预后与地区贫困分别贡献多少？',data:'Victoria Lung Cancer Registry个体数据；地区贫困、偏远和污染数据',design:'登记队列的Bayesian空间多水平研究',sample:'2011—2016年3330例NSCLC患者',flow:'个体临床因素\n→ 地区社会与环境因素\n→ 空间多水平Logistic模型\n→ 分步加入变量\n→ 比较地理方差变化',result:'及时且确定性治疗与较低2年死亡相关，未治疗、临床预后和地区贫困解释部分地理差异。',innovation:'展示了个体临床变量与地区空间变量联合建模，能减轻纯生态研究的解释局限。',limitations:'观察性研究仍可能有未测混杂；澳大利亚医疗体系与广东不同。',reuse:'若广东以后能链接病例分期、治疗与随访，优先升级为个体-区县多水平空间模型。',url:'https://doi.org/10.1002/ijc.33343'},
{id:'E06',module:'社会环境与癌症负担关联',priority:5,title:'Small Area Disease Mapping of Cancer Incidence in British Columbia Using Bayesian Spatial Models and the smallareamapp R Package',authors:'Simkin J, Dummer TJB, Erickson AC, et al.',journal:'Frontiers in Oncology',year:2022,methods:['BYM2','INLA','Moran’s I','超阈值概率','癌症登记'],question:'如何把癌症登记计数转成稳定的小区域RR图，并用后验概率识别可信高风险区？',data:'British Columbia癌症登记；2011—2018年肺、乳腺、宫颈和结直肠癌',design:'小区域Bayesian疾病制图应用',sample:'218个社区卫生服务区；多癌种数万病例',flow:'年龄别期望数与SIR\n→ Moran’s I\n→ Queen邻接BYM2\n→ INLA\n→ 后验RR/CrI\n→ P(RR>1.1)超阈值图\n→ 后验预测检查',result:'BYM2在癌症计数稀疏时提供更稳定风险估计，超阈值概率比仅看RR更适合标记高风险区。',innovation:'从登记数据、间接标化、Moran到BYM2和诊断的完整可复现工作流。',limitations:'空间平滑对中等RR和低期望数热点的敏感性有限；邻接和阈值需敏感性分析。',reuse:'最适合直接复现广东区县癌症风险图的应用论文，建议列为第一批精读与代码复现。',url:'https://doi.org/10.3389/fonc.2022.833265'}
,
{id:'B06',module:'贝叶斯疾病制图与空间回归',priority:5,title:'A Shared Component Model for Detecting Joint and Selective Clustering of Two Diseases',authors:'Knorr-Held L, Best NG',journal:'Journal of the Royal Statistical Society: Series A',year:2001,methods:['Shared component model','多癌种制图','共同风险面','疾病特异风险'],question:'多个主要癌症同时分析时，怎样分离共同空间聚集与各癌种特异的高风险格局？',data:'多个癌种的地区病例计数、期望数和邻接结构',design:'多变量Bayesian疾病制图方法',sample:'德国544个地区口腔癌与食管癌死亡案例',flow:'各癌种Poisson计数模型\n→ 共享空间潜在成分\n→ 癌种特异空间成分\n→ 权重/尺度参数\n→ 联合后验估计\n→ 共同与特异风险图',result:'共享成分模型可识别可能反映共同危险因素的联合聚集，同时保留各癌种独有的空间风险。',innovation:'避免对多个癌种逐一制图而忽略癌种间相关性，特别适合“主要癌症”联合空间分析。',limitations:'共享成分的病因解释依赖模型设定，癌种过多时辨识和计算复杂；不能仅凭共享地图断言共同病因。',reuse:'广东可先对肺、肝、胃、结直肠、乳腺与鼻咽癌分别建模，再用共享成分模型探索共同和特异热点。',url:'https://doi.org/10.1111/1467-985X.00187'},
{id:'B07',module:'贝叶斯疾病制图与空间回归',priority:4,title:'Assessing Spatial Confounding in Cancer Disease Mapping Using R',authors:'Azevedo DRM, Bandyopadhyay D, Prates MO, Abdel-Salam AG, Garcia D',journal:'Cancer Reports',year:2020,methods:['空间混杂','Restricted spatial regression','RHZ','HH','SPOCK'],question:'当GDP、PM2.5或医疗可及性与空间随机效应高度重叠时，协变量效应为何会改变，怎样做敏感性分析？',data:'区域癌症计数、空间协变量与邻接结构',design:'空间混杂方法比较与R实现',sample:'两个癌症疾病制图数据集及模拟',flow:'非空间计数模型\n→ 标准CAR/BYM模型\n→ 检查固定效应与空间效应重叠\n→ RHZ/HH/SPOCK受限空间回归\n→ 比较系数、区间与拟合',result:'不同空间混杂处理方法会明显改变协变量系数与不确定性，必须把它作为敏感性分析而非自动校正步骤。',innovation:'面向癌症疾病制图系统比较多种空间混杂处理策略并提供实现思路。',limitations:'受限空间回归本身存在推断争议；不能以获得更显著系数作为选模型标准。',reuse:'广东关联分析至少比较非空间、BYM2和一种空间混杂处理模型，并以预测检查和科学解释共同判断。',url:'https://doi.org/10.1002/cnr2.1263'}
];

const METHOD_MAP=[
['广东区县是否存在整体聚集？','经验Bayes/BYM2风险 + Global Moran’s I'],
['高风险区县具体在哪里？','Local Moran’s I + FDR + 稳定性分析'],
['哪个地区在什么年份异常升高？','Poisson时空扫描：RR、LLR、Monte Carlo'],
['小区县病例少、粗率很抖？','BYM2 + INLA + 后验RR/超阈值概率'],
['医疗资源是否真正可达？','路网时间 + E2SFCA/3SFCA，而非仅最近距离'],
['可及性、GDP、PM2.5如何关联负担？','Poisson/负二项Bayesian空间层级回归'],
['多个癌种有共同热点吗？','Shared component multivariate disease mapping'],
['关联是否随地区而变化？','时空交互；MGWR仅作探索性补充'],
['能否解释为个人危险因素？','不能直接；区域研究需警惕生态谬误与空间混杂']
];
const LEARNING_PATH=['登记质控与可比面板','病例数+人口人时','Global/Local Moran','Poisson时空扫描','BYM2疾病制图','路网与E2SFCA','Bayesian空间关联','敏感性与生态解释'];

const MODULE_DEEP_DIVE={
'空间自相关与聚集探测':{why:'Global Moran、Local Moran和SaTScan并非互相替代：它们分别回答整体是否聚集、局部在哪里聚集、哪个可变窗口的病例超出期望。',estimand:'空间自相关统计量I；区县LISA类型；扫描窗口的相对风险RR、对数似然比LLR及Monte Carlo P值。',variables:['稳定的区县风险指标或病例计数','人口人时/期望病例','区县邻接矩阵或质心','年份、性别、年龄分层','扫描窗口和最大空间/时间比例'],assumptions:['空间权重能代表合理邻近关系','Poisson扫描中病例数条件于人口/期望数','登记覆盖在扫描区域与时间内可比','检验方案和窗口参数不是看结果后任意挑选'],diagnostics:['Queen/Rook/距离权重敏感性','LISA做FDR或置换校正','SaTScan最大窗10%/25%/50%比较','圆形/椭圆或替代扫描形状比较','检查热点是否由单个小分母区县驱动'],replication:['先算年龄性别期望数，再运行扫描','同时保存RR、LLR、P值、窗口范围和重叠规则','把多组参数结果做稳定性叠加图','聚集探测用于筛查，不自动等于病因证据'],reading:'始终区分global clustering与cluster detection，并检查作者是否处理率不稳定、多重比较和参数敏感性。',extensions:'可加入柔性扫描、贝叶斯聚类边界、变化点和前瞻性时空监测。'},
'贝叶斯疾病制图与空间回归':{why:'区县癌症病例是计数且人口规模不同。Bayesian空间层级模型能用邻区信息稳定风险，同时保留不确定性，并把医疗、社会和环境协变量纳入同一模型。',estimand:'区县后验RR、95%可信区间、P(RR>1或1.1)、协变量后验率比，以及结构化空间方差比例φ。',variables:['病例计数Y','期望数E或人口offset','邻接矩阵W','年份与时空索引','标准化协变量及合理滞后','登记质量和覆盖变量'],assumptions:['Poisson均值/负二项离散结构合理','CAR邻接反映残余空间相关','协变量测量与时间顺序合理','区域效应是生态关联而非个体因果效应','先验不会主导稀疏数据结论'],diagnostics:['过度离散和零值检查','后验预测检查/PIT/CPO','残差Moran’s I','WAIC/DIC/LOO模型比较','VIF/相关矩阵与空间混杂敏感性','先验、邻接、时间滞后和缺失机制敏感性'],replication:['首选R-INLA的BYM2+PC prior','报告粗SIR与平滑RR对照','主模型用病例计数和log(E) offset','协变量按有意义尺度标准化并报告率比','输出完整后验而不只报显著性'],reading:'重点盯住模型层级、offset、空间效应参数化、先验、后验诊断与生态解释边界。',extensions:'可扩展到多癌种共享成分模型、INLA-SPDE、个体-地区多水平模型和测量误差模型。'},
'医疗资源空间可及性':{why:'最近医院时间只测地理接近，不考虑医院容量、服务人口和居民对机构的竞争。FCA/重力模型把供给、需求与出行阻抗结合起来。',estimand:'每个居民点或区县的最短时间、加权平均时间、供需比型E2SFCA/3SFCA可及性以及城乡差异。',variables:['医疗机构经纬度与等级','肿瘤专科床位/医生/放疗设备等容量','人口网格或需求点','可路由道路网络与交通速度','汽车/公共交通/步行模式比例','距离衰减和服务圈阈值'],assumptions:['机构容量可代表可提供的肿瘤服务','路网速度与交通模式接近研究时期实际','服务阈值和衰减函数适合广东城乡','潜在可及性不等于实际利用或医疗质量'],diagnostics:['与真实就医流或患者来源校准','高峰/平峰、城乡和多交通模式敏感性','不同容量定义与阈值比较','检查区县质心近似造成的MAUP与聚合偏差'],replication:['先用Dijkstra/OSRM获得需求点—机构时间矩阵','同时报告最近时间和E2SFCA，避免单指标结论','用人口网格聚合到区县而非直接用区县质心','保留医院容量和服务能力版本记录'],reading:'先判断论文测量的是接近性、供给可用性、潜在可及性还是真实利用，再比较指标。',extensions:'可加入跨市就医、医院质量、转诊层级、拥堵、费用和患者选择模型。'},
'社会环境与癌症负担关联':{why:'GDP、PM2.5、夜间灯光、土地覆盖和医疗可及性通常都具有强空间结构，普通回归会低估不确定性并混淆空间趋势。',estimand:'协变量每增加一个有意义单位对应的发病/死亡率比及其后验分布；地区/时间异质效应；可解释的残余空间变异。',variables:['癌症计数与期望数','医疗可及性指标','GDP/教育/城镇化/夜间灯光','PM2.5与土地覆盖','吸烟等可得混杂因素','时间滞后、登记质量和空间邻接'],assumptions:['暴露先于结局且时间窗口合理','关键区域层面混杂因素已控制','共线性和空间混杂可管理','生态关联不外推到个体','缺失和测量误差不会产生系统性空间偏倚'],diagnostics:['相关矩阵/VIF和变量降维','逐块建模：基础→社会经济→环境→医疗','残差空间相关与后验预测','不同滞后和空间尺度','非线性/交互与稳健先验','负对照或替代结局（可行时）'],replication:['预先画DAG区分混杂、媒介和代理变量','主模型用BYM2计数回归，MGWR只做探索','避免把同时期医疗资源与发病率直接解释为资源导致发病','发病和死亡分开建模；死亡更可能受诊疗可及性影响'],reading:'最重要的是区分空间预测、生态关联和因果解释三个层级。统计显著不等于可干预因果关系。',extensions:'有个体病例时可做多水平空间模型；有政策或设施变动时可考虑空间DID/事件研究。'}
};
const DEEP_DIVE={};
function getDeepDive(p){return {...(MODULE_DEEP_DIVE[p.module]||{}),...(DEEP_DIVE[p.id]||{})};}
